title: Shad Humydee # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Artificial Intelligence Engineer | Data Science Enthusiast<br>
  Second description 
  <br>Taking the extra mile to always learn something new.<br>
  <a href="https://www.linkedin.com/in/shad-humydee">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
